name: AI Content Draft PR

on:
  workflow_dispatch:
  schedule:
    - cron: "0 13 * * 1-5"

jobs:
  open-draft-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: pnpm
      - run: pnpm install --frozen-lockfile
      - name: Generate draft summary (placeholder)
        run: pnpm tsx scripts/plan-topics.ts --keyword "AI content"
      - name: Create pull request (placeholder)
        run: |
          echo "Would run a script that copies approved drafts into posts and opens a PR"
